### ISSUE TITLE
허용 앱 설정 리스트에서 우리 앱 설정 제외하기 

### ISSUE THREAD

**Issue by 1chanhue1** [Team-Rocket-nbc-team2/CosmicDetox#106]
### **오류내용**

허용 앱 설정에서 우리 앱도 설정이 가능. 잠깐 쉬기에서 우리 앱 클릭하고 사용 시간 지나면 오버레이뷰 계속 떠있을 거 예상

### **해결 방안**

우리 앱은 허용 앱 설정에서 제외

**Comment by ImGaram** [comment]
마이페이지의 허용 앱 추가에서 우리 앱만 제외시키면 내쪽에서 우리 앱이 뜨지는 않을 듯.

**Comment by seojw0124** [comment]
이건 내가 했어
