### ISSUE TITLE
디자인 피드백(예시)

### ISSUE THREAD

**Issue by ImGaram** [Team-Rocket-nbc-team2/CosmicDetox#32]
## 작업할 내용
- [x] : textView line spacing 적용
- [ ] #80
- [x] : 버튼 좌우 행렬 정렬

**Comment by kkevi** [comment]
버튼 좌우는 안 해도 괜찮음! 이미 되어있는 것으로 파악함~
line spacing은 마이페이지에서 트로피가 비어있는 문구와 BottomSheet에서 리스트가 비어있을 때 나오는 문구에 적용 필요함!
Vector 이미지는 시간될 때 여유롭게 바꾸면 됨!
